project:
  type: "website"
  title: "GEOMATICA BASICA 2024"
  output-dir: _output
  render:
    - "index.qmd"
    - "2024/*.qmd"
    - "2024/weeks/week01/*.qmd"
    - "2024/weeks/week02/*.qmd"

website:
  title: "GEOMATICA BASICA 2024"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card: 
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/ARS-1.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: 2024/index.qmd
        text: "🏠 Home"
      - href: 2024/syllabus.qmd
        text: "📓 Syllabus"
      # - href: 2024/communication.qmd
      #   text: "📟 Communication"
      # - href: 2024/assignments.qmd
      #   text: "✍️ Assignments"
      #   contents:
      #     - href: 2024/assignments/assignment01.qmd
      #       text: "📝 Assignment 01"
      #     - href: 2024/assignments/assignment02.qmd
      #       text: "📝 Assignment 02"
      #     - href: 2024/assignments/group_project.qmd
      #       text: "👥 Group Project"
      - section: "🗓️ Weeks"
        contents:
         - href: 2024/weeks/week01/page.qmd
           text: Week 01
           contents:
             - href: 2024/weeks/week01/page.qmd
               text: 👨‍🏫 Lecture Material
         - href: 2024/weeks/week02/page.qmd
           text: Week 02
           contents:
             - href: 2024/weeks/week02/page.qmd
               text: 👨‍🏫 Lecture Material

  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2024, IALS" 



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Ivan Lizarazo
    author-meta: Ivan Lizarazo
    date-format: "DD MMMM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:ials\.github\.io\/|localhost)

    theme:
      light: 
        - journal
        - css/custom.scss # I use this just to change the default colour
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true

#margin-header: 
#![](/figures/icons/UNAL-1.png)

