---
title: "🗓️ Week 03 - Coordinate systems  and map projections"
---

In this week, we will cover the following topics:

**Theoretical topics**:

- Geodetic concepts
- Coordinates reference systems (CRS)
- Map projections

**Practical exercise**:

-  Download [DANE population data per municipalities](https://www.dane.gov.co/files/censo2018/proyecciones-de-poblacion/Municipal/DCD-area-proypoblacion-Mun-2020-2035-ActPostCOVID-19.xlsx)

-  Create a table with 2024 population  

-  Join your department's municipalities to the population table

-  Review [socio-economic data for your department](https://www.dane.gov.co/index.php/actualidad-dane/5607-informacion-economica-y-sociodemografica-desagregada-a-nivel-municipal?highlight=WyJwb2JsYWNpXHUwMGYzbiIsInBvYmxhY2lvbiIsInBvYmxhY2lvbmVzIiwicG9yIiwicG9yb3NhcyIsIm11bmljaXBpb3MiLCJtdW5pY2lwaW8iXQ==) and summarize it for your report

## 👨‍🏫 Lecture Slides 

You can find the slides [here](https://docs.google.com/presentation/d/1teYd09bo9BH2CK0b3G9Z77jnxcDjmTJ-/edit?usp=sharing&ouid=101294548671143516389&rtpof=true&sd=true)

🎥 

## 📚 Recommended Reading 

Read:

- [Proyección Cartográfica Colombia](https://origen.igac.gov.co/docs/ABC_Nueva_Proyeccion_Cartografica_Colombia.pdf) and take notes

- [What are ellipsoid and geoid heights?](https://help.propelleraero.com/hc/en-us/articles/19383617598743-What-Are-Ellipsoid-and-Geoid-Heights#h_01HT5Q4VEN0WF0AW4MXH9P459C)

## ✍️ Coursework

🚧 In your  notebook,  answer the following questions 🚧

### Part 1
::: {.callout-important collapse=true}
1. What are the geometric parameters associated to the ellipsoid GRS 80?
2. What is the geoid?
3. What are the most important characteristics of the geoid?
:::

### Part 2
::: {.callout-important collapse=true}
4. What is a datum?
5. What is the datum MAGNA-SIRGAS?
6. Describe  the Colombian map projection (EPSG:9377)

:::


